# Generated by Django 5.0.6 on 2026-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='action_required',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='appointment_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='current_step',
            field=models.CharField(blank=True, default='Pending', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='last_screenshot',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='step_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='total_steps',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='passport_images/'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='passport_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING_FOR_USER', 'Waiting for User'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
